name: BuildWxread

concurrency:
  group: ${{ github.workflow }} # 使用工作流名称作为并发组的key
  cancel-in-progress: true    # 取消任何正在进行的相同并发组的工作流

permissions:
  contents: write

# 触发条件
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
      - '.gitignore'
      - '.git/**'
      - 'LICENSE'
      - 'Makefile'
      - 'exe/**'
    branches:
      - main

jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 运行步骤
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.7'
      - uses: actions/checkout@v4
        with:
          path: build

      - uses: actions/checkout@v4
        with:
          ref: release
          path: release

      - run: go install github.com/mitchellh/gox@latest # 安装 gox
      - name: Build
        run: |
          cd build || exit 1
          make build-linux-amd64

      - name: Copy Files
        run: |
          cp -r build/exe/* release/

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd release || exit 1
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout --orphan latest_branch
          git pull
          git add -A
          git commit -am "build wxread"
          git branch -D release
          git branch -m release
          git push -f origin release

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 8